[package]
name = "simple-static-files-server"
version = "0.1.0"
authors = ["Yana Agun Siswanto <yana.developer@gmail.com>"]
edition = "2018"

[dependencies.config]
version = "0.9.2"

[dependencies.rouille]
version = "3.0.0"
features = ["ssl"]
